### ISSUE TITLE
facing problem while flashing PIC16F18875

### ISSUE THREAD

**Issue by embhobbb** [jaromir-sukuba/a-p-prog#10] opened 2020-10-08 02:28 UTC
i am using your programmer to flash PIC16F18875 but i am getting error as follows.
```
E:\DIY\Programmer\PIC Programmer using Arduino\picProg\sw>pp3.exe -c COM4 -s 1700 -t 16f18875 PwmGen.X.production.hex
PP programmer, version 0.99
Sleeping for 1700 ms while arduino bootloader expires
Wrong device ID: 0000, expected: 306d
Check for connection to target MCU, exiting now
```

I could able to flash other controller PIC16F1847 but not this one. 
PIC16F18875 has MCLR resistor of 10K connected and pulled up to VDD. other than this i have not connected anything.

**Comment by embhobbb** [comment] 2020-10-08 02:28
```
pp3.exe -c COM4 -s 1700 -t 16f18875 PwmGen.X.production.hex
PP programmer, version 0.99
Sleeping for 1700 ms while arduino bootloader expires
Wrong device ID: 0000, expected: 306d
Check for connection to target MCU, exiting now
```

**Comment by jaromir-sukuba** [comment] 2020-11-27 22:48
This looks like a duplicate of issue #9 , closing.

**Closed by jaromir-sukuba** 2020-11-27 22:48 UTC

**Comment by embhobbb** [comment] 2020-12-01 11:23
Thanks for your reply. My connection is very simple which works with pickit3. But my pickit3 is not working now. I found your project very helpful. Here are the commands i was trying..
E:\DIY\Programmer\PIC Programmer using Arduino\picProg\sw>pp3.exe -c COM12  -s 1700 -t 16f18875 test.X.production.hex
PP programmer, version 0.99
Sleeping for 1700 ms while arduino bootloader expires
Device ID: 306d
Programming FLASH (16384 B in 256 pages)
Programming config
Verifying FLASH (16384 B in 256 pages)
Verifying config
Error at 0x4007 E:0x1F R:0x3F

**Comment by embhobbb** [comment] 2020-12-01 11:34
[test.X.production.txt](https://github.com/jaromir-sukuba/a-p-prog/files/5622251/test.X.production.txt)

here is the attached hex file. Please change the extention from .txt to .hex.
